[versions]
accompanistPermissions = "0.23.0"
activityComposeVersion = "1.9.0"
agp = "8.7.3"
androidPdfViewer = "3.2.0-beta.1"
androidPdfViewerVersion = "2.8.2"
androidxActivityCompose = "1.9.0"
appRemote = "0.7.2"
appRemoteVersion = "0.7.0"
coilCompose = "2.2.2"
compiler = "4.13.2"
documentfile = "1.0.1"
kotlin = "1.9.0"
coreKtx = "1.13.1"
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
lifecycleRuntimeKtx = "2.8.0"
activityCompose = "1.9.0"
composeBom = "2024.05.00"
firebaseStorageKtx = "21.0.0"
material = "1.6.7"
material3 = "1.3.0-alpha01"
materialVersion = "1.6.7"
navigationCompose = "2.7.7"
playServicesAuth = "21.2.0"
roomCommon = "2.6.1"
roomKtx = "2.6.1"
appcompat = "1.6.1"
roomKtxVersion = "2.6.1"
roomRuntime = "2.6.1"
runtime = "1.6.7"
runtimeLivedata = "1.6.7"
ui = "1.6.7"
uiLayout = "1.3.0"
uiTooling = "1.6.7"
uiToolingPreview = "1.6.7"
uiVersion = "1.6.7"
firebaseFirestoreKtx = "25.0.0"
navigationComposeVersion = "2.7.7"
navigationFragmentKtx = "2.7.7"
navigationRuntimeKtx = "2.7.7"
composePreviewRenderer = "0.0.1-alpha01"
media3Ui = "1.3.1"
androidthings = "1.0"
firebaseDatabaseKtx = "21.0.0"
workRuntimeKtx = "2.9.1"
navigationRuntimeAndroid = "2.9.4"

[libraries]
accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanistPermissions" }
android-pdf-viewer = { module = "com.github.barteksc:android-pdf-viewer", version.ref = "androidPdfViewer" }
android-pdf-viewer-v282 = { module = "com.github.barteksc:android-pdf-viewer", version.ref = "androidPdfViewerVersion" }
androidx-activity-compose-v130 = { module = "androidx.activity:activity-compose", version.ref = "androidxActivityCompose" }
androidx-activity-compose-v140rc01 = { module = "androidx.activity:activity-compose", version.ref = "activityComposeVersion" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-documentfile = { module = "androidx.documentfile:documentfile", version.ref = "documentfile" }
androidx-material = { module = "androidx.compose.material:material", version.ref = "material" }
androidx-material-v130 = { module = "androidx.compose.material:material", version.ref = "materialVersion" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigationCompose" }
androidx-room-ktx-v240 = { module = "androidx.room:room-ktx", version.ref = "roomKtxVersion" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "roomRuntime" }
androidx-runtime = { module = "androidx.compose.runtime:runtime", version.ref = "runtime" }
androidx-runtime-livedata = { module = "androidx.compose.runtime:runtime-livedata", version.ref = "runtimeLivedata" }
androidx-ui-layout = { module = "androidx.compose.ui:ui-layout", version.ref = "uiLayout" }
androidx-ui-v130 = { module = "androidx.compose.ui:ui", version.ref = "uiVersion" }
app-remote = { module = "com.spotify.android:app-remote", version.ref = "appRemote" }
app-remote-v070 = { module = "com.spotify.android:app-remote", version.ref = "appRemoteVersion" }
coil = { module = "io.coil-kt:coil", version.ref = "coilCompose" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coilCompose" }
compiler = { module = "com.github.bumptech.glide:compiler", version.ref = "compiler" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
firebase-storage-ktx = { group = "com.google.firebase", name = "firebase-storage-ktx", version.ref = "firebaseStorageKtx" }
androidx-room-common = { group = "androidx.room", name = "room-common", version.ref = "roomCommon" }
androidx-room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "roomKtx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material3 = { module = "com.google.android.material3:material3", version.ref = "material3" }
play-services-auth = { module = "com.google.android.gms:play-services-auth", version.ref = "playServicesAuth" }
ui = { module = "androidx.compose.ui:ui", version.ref = "ui" }
ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "uiTooling" }
ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "uiToolingPreview" }
firebase-firestore-ktx = { group = "com.google.firebase", name = "firebase-firestore-ktx", version.ref = "firebaseFirestoreKtx" }
navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigationComposeVersion" }
androidx-navigation-fragment-ktx = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigationFragmentKtx" }
androidx-navigation-runtime-ktx = { group = "androidx.navigation", name = "navigation-runtime-ktx", version.ref = "navigationRuntimeKtx" }
compose-preview-renderer = { group = "com.android.tools.compose", name = "compose-preview-renderer", version.ref = "composePreviewRenderer" }
androidx-media3-ui = { group = "androidx.media3", name = "media3-ui", version.ref = "media3Ui" }
androidthings = { group = "com.google.android.things", name = "androidthings", version.ref = "androidthings" }
firebase-database-ktx = { group = "com.google.firebase", name = "firebase-database-ktx", version.ref = "firebaseDatabaseKtx" }
androidx-work-runtime-ktx = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "workRuntimeKtx" }
androidx-navigation-runtime-android = { group = "androidx.navigation", name = "navigation-runtime-android", version.ref = "navigationRuntimeAndroid" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
jetbrainsKotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

